name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - master  # ou o nome da sua branch principal

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./  # Pasta do seu projeto
          server-dir: /htdocs/  # Pasta no InfinityFree
